### ISSUE TITLE
Mac usage - zim to txt

### ISSUE THREAD

**Issue by giuliagrisot** [DavidNemeskey/zim_to_corpus#14]
I am rather a beginner with coding and not so much of an IT expert, and I don’t quite understand how to use the tool (on a Mac).
Is there any chance you could give me a heads up and a few step by step terminal lines to go from a zim file to a folder with many txt files?

**Comment by DavidNemeskey** [comment]
Given that I have only ever released Linux binaries, the best way would be to use the docker image. You will have to [install docker first](https://docs.docker.com/desktop/install/mac-install/), and then the commands are actually in the README. To recap:
```
docker create zim_to_dir
```
Then, you can run the container with
```
docker run --rm --mount type=bind,source=/home/user/data/,target=/data zim_to_dir -i /data/wikipedia_hu_all_mini.zim -o /data/hu_mini/ -d 2000
```
, where the input is `/home/user/data/wikipedia_hu_all_mini.zim` and the output will be written to `/home/user/data/hu_mini/`.

**Comment by DavidNemeskey** [comment]
@giuliagrisot I'm closing this issue. Let me know if you still have questions.
