### ISSUE TITLE
The page Lábjegyzet is missing

### ISSUE THREAD

**Issue by DavidNemeskey** [DavidNemeskey/zim_to_corpus#7]
Probably because Lábjegyzet (Footnote) is included in the list of sections to delete. Also, the page is not missing, but is completely empty, which causes problems to the [cc_corpus](https://github.com/DavidNemeskey/cc_corpus) scripts.

**Comment by DavidNemeskey** [comment]
As the linked issue shows, there are other empty units in the output of convert.py.

**Comment by DavidNemeskey** [comment]
@dlazesz I am now removing empty units before converting the files to tsv. Please take a look at the corpus again, there should be no more empty units in it.

**Comment by dlazesz** [comment]
No more empty units. :tada: Great work! Thank you!
You can close the issue.
